services:
  db:
    image: postgres:16
    env_file:
      - ./.env
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db

    env_file:
      - ./.env
    volumes:
      - ./web-src/public:/app/public
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./web-src
      dockerfile: Dockerfile
    depends_on:
      - app
    #volumes:
    #  - ./web-src:/app
    ports:
      - "5173:5173"